import type { GenerationTask } from "./types";

const now = Date.now();

export const QUEUE_SEED: GenerationTask[] = [
  {
    id: "task-001",
    type: "image",
    model: "Flux Pro",
    prompt: "Футуристичный интерьер коворкинга, warm coal, cinematic lighting",
    createdAt: now - 1000 * 60 * 18,
    startedAt: now - 1000 * 60 * 2,
    status: "running",
    progress: 42,
    credits: 18,
    etaSeconds: 54,
  },
  {
    id: "task-002",
    type: "video",
    model: "Kling 2.1",
    prompt: "Камера облетает неоновый город, дождь, 6 секунд",
    createdAt: now - 1000 * 60 * 16,
    startedAt: now - 1000 * 60 * 3,
    status: "running",
    progress: 27,
    credits: 65,
    etaSeconds: 1680,
  },
  {
    id: "task-003",
    type: "text",
    model: "GPT-4.1",
    prompt: "Напиши onboarding flow для SaaS продукта на русском языке",
    createdAt: now - 1000 * 60 * 14,
    status: "queued",
    progress: 0,
    credits: 5,
    etaSeconds: 24,
  },
  {
    id: "task-004",
    type: "audio",
    model: "Suno V4",
    prompt: "Lo-fi beat with soft piano and vinyl texture, 30 seconds",
    createdAt: now - 1000 * 60 * 13,
    status: "queued",
    progress: 0,
    credits: 34,
    etaSeconds: 135,
  },
  {
    id: "task-005",
    type: "image",
    model: "Ideogram",
    prompt: "Постер для фуд-фестиваля, яркий flat style",
    createdAt: now - 1000 * 60 * 12,
    status: "queued",
    progress: 0,
    credits: 15,
    etaSeconds: 47,
  },
  {
    id: "task-006",
    type: "text",
    model: "Claude Sonnet",
    prompt: "Сгенерируй 10 вариантов рекламного оффера для финтеха",
    createdAt: now - 1000 * 60 * 10,
    completedAt: now - 1000 * 60 * 8,
    status: "done",
    progress: 100,
    credits: 7,
    etaSeconds: 0,
    outputUrl: "#",
  },
  {
    id: "task-007",
    type: "image",
    model: "Midjourney V7",
    prompt: "Логотип для студии motion design, minimal brutalism",
    createdAt: now - 1000 * 60 * 9,
    completedAt: now - 1000 * 60 * 5,
    status: "done",
    progress: 100,
    credits: 21,
    etaSeconds: 0,
    outputUrl: "#",
  },
  {
    id: "task-008",
    type: "video",
    model: "Runway Gen-4",
    prompt: "Съёмка продукта на вращающейся подставке, студийный свет",
    createdAt: now - 1000 * 60 * 8,
    completedAt: now - 1000 * 60 * 3,
    status: "failed",
    progress: 61,
    credits: 48,
    etaSeconds: 0,
    errorMessage: "Модель временно недоступна",
  },
  {
    id: "task-009",
    type: "audio",
    model: "ElevenLabs",
    prompt: "Озвучка рекламного ролика, мужской голос, 15 секунд",
    createdAt: now - 1000 * 60 * 7,
    status: "queued",
    progress: 0,
    credits: 12,
    etaSeconds: 98,
  },
  {
    id: "task-010",
    type: "text",
    model: "Gemini 2.5 Pro",
    prompt: "Составь контент-план на 2 недели для AI-агентства",
    createdAt: now - 1000 * 60 * 6,
    status: "canceled",
    progress: 0,
    credits: 6,
    etaSeconds: 0,
  },
];
